//! Numeric correctness tests for cuda-oxide kernels vs. PyTorch reference.
//!
//! These tests require a physical A100 GPU and are marked `#[ignore]` so they
//! are skipped in CI. Run them on Narval with:
//!
//! ```bash
//! cargo test --test correctness -- --ignored
//! ```

use approx::assert_abs_diff_eq;
use kernelserve_kernels::{FusedAttn, RmsNorm};

const EPS: f32 = 1e-4;

/// Compare RmsNorm output against the PyTorch reference computed offline.
///
/// Reference values are generated by `kernels/triton/rms_norm.py` with the
/// same input seed and stored as hard-coded constants here for determinism.
#[test]
#[ignore = "requires A100 GPU"]
fn test_rms_norm_vs_pytorch() {
    // TODO: load reference input/output tensors from a fixture file
    // TODO: call RmsNorm::new(1e-5).forward(&input, &weight)
    // TODO: assert_abs_diff_eq!(output[i], reference[i], epsilon = EPS)
    let kernel = RmsNorm::new(1e-5);
    let input = vec![1.0_f32; 512];
    let weight = vec![1.0_f32; 512];
    let _result = kernel.forward(&input, &weight);
    // placeholder assertion — replace with real reference values
    assert_abs_diff_eq!(1.0_f32, 1.0_f32, epsilon = EPS);
}

/// Compare FusedAttn output against the PyTorch reference.
#[test]
#[ignore = "requires A100 GPU"]
fn test_fused_attn_vs_pytorch() {
    // TODO: load reference qkv tensor from a fixture file
    // TODO: call FusedAttn::new(8, 64).forward(&qkv)
    // TODO: assert_abs_diff_eq! element-wise with epsilon = EPS
    let kernel = FusedAttn::new(8, 64);
    let qkv = vec![0.0_f32; 8 * 512 * 3 * 8 * 64];
    let _result = kernel.forward(&qkv);
    assert_abs_diff_eq!(1.0_f32, 1.0_f32, epsilon = EPS);
}
