//! Numeric correctness tests for cuda-oxide kernels vs. PyTorch reference.
//!
//! These tests require a physical A100 GPU and are marked `#[ignore]` so they
//! are skipped in CI. Run them on Narval with:
//!
//! ```bash
//! cargo test --test correctness -- --ignored
//! ```

use kernelserve_kernels::{FusedAttn, RmsNorm};

/// Max absolute error budget (fp32 vs PyTorch reference).
const EPS: f32 = 1e-4;

/// Compare RmsNorm output against the PyTorch reference fixture.
///
/// Fixture generated by:
/// ```bash
/// python kernels/triton/rms_norm.py generate --batch 4 --hidden_dim 4096 --seed 42
/// ```
#[test]
#[ignore = "requires A100 GPU"]
fn test_rms_norm_vs_pytorch() {
    use ndarray::{Array1, Array2};
    use ndarray_npy::NpzReader;
    use std::fs::File;

    let fixture = "tests/fixtures/rms_norm_4x4096.npz";
    let f = File::open(fixture).unwrap_or_else(|e| panic!("fixture not found at {fixture}: {e}"));
    let mut npz = NpzReader::new(f).unwrap();

    let input: Array2<f32> = npz.by_name("input.npy").unwrap();
    let weight: Array1<f32> = npz.by_name("weight.npy").unwrap();
    let reference: Array2<f32> = npz.by_name("output.npy").unwrap();

    let (input_vec, _) = input.into_raw_vec_and_offset();
    let (weight_vec, _) = weight.into_raw_vec_and_offset();
    let (reference_vec, _) = reference.into_raw_vec_and_offset();

    let result = RmsNorm::new(1e-5)
        .forward(&input_vec, &weight_vec)
        .expect("RmsNorm::forward failed");

    assert_eq!(result.len(), reference_vec.len(), "output length mismatch");

    let max_err = result
        .iter()
        .zip(&reference_vec)
        .map(|(got, want)| (got - want).abs())
        .fold(0.0_f32, f32::max);

    assert!(
        max_err < EPS,
        "max absolute error {max_err:.2e} ≥ threshold {EPS:.2e}"
    );
}

/// Compare FusedAttn output against the PyTorch reference.
#[test]
#[ignore = "requires A100 GPU"]
fn test_fused_attn_vs_pytorch() {
    // TODO: load reference qkv tensor from a fixture file
    // TODO: call FusedAttn::new(8, 64).forward(&qkv)
    // TODO: assert element-wise max abs error < EPS
    let _kernel = FusedAttn::new(8, 64);
    // TODO: load fixture, call forward, assert max abs error < EPS
}
