"""CPU-path correctness test for the kernelserve PyO3 binding.

Runs without a GPU — tests the cpu_ref::rms_norm_cpu Rust implementation
against the fixture generated by PyTorch (kernels/cuda_oxide/tests/fixtures/).
"""

from __future__ import annotations

import pathlib

import numpy as np
import pytest
import torch

import kernelserve

pytestmark = pytest.mark.skipif(
    not kernelserve._CORE_AVAILABLE,
    reason="kernelserve_core not built — run: make build-bindings",
)

FIXTURE = pathlib.Path("kernels/cuda_oxide/tests/fixtures/rms_norm_4x4096.npz")
MAX_ABS_ERR = 1e-4


@pytest.fixture(scope="module")
def fixture_data():
    if not FIXTURE.exists():
        pytest.skip(f"fixture not found: {FIXTURE}")
    data = np.load(FIXTURE)
    return (
        torch.from_numpy(data["input"]).float(),
        torch.from_numpy(data["weight"]).float(),
        torch.from_numpy(data["output"]).float(),
    )


def test_rms_norm_cpu_vs_fixture(fixture_data, monkeypatch):
    """CPU reference path must match the PyTorch-generated fixture within 1e-4."""
    monkeypatch.setenv("KERNELSERVE_DEVICE", "cpu")
    import kernelserve

    x, w, ref = fixture_data
    out = kernelserve.rms_norm(x, w, eps=1e-5)
    max_err = float((out - ref).abs().max())
    assert max_err < MAX_ABS_ERR, (
        f"max absolute error {max_err:.2e} exceeds threshold {MAX_ABS_ERR:.1e}"
    )


def test_rms_norm_output_shape(fixture_data, monkeypatch):
    monkeypatch.setenv("KERNELSERVE_DEVICE", "cpu")
    import kernelserve

    x, w, _ = fixture_data
    out = kernelserve.rms_norm(x, w)
    assert out.shape == x.shape


def test_rms_norm_synthetic_cpu(monkeypatch):
    """Synthetic correctness check against torch.nn.functional.rms_norm."""
    monkeypatch.setenv("KERNELSERVE_DEVICE", "cpu")
    import kernelserve

    torch.manual_seed(0)
    x = torch.randn(8, 512, dtype=torch.float32)
    w = torch.ones(512, dtype=torch.float32)

    ref = torch.nn.functional.rms_norm(x, (512,), weight=w, eps=1e-5)
    out = kernelserve.rms_norm(x, w, eps=1e-5)

    max_err = float((out - ref).abs().max())
    assert max_err < MAX_ABS_ERR, (
        f"max absolute error {max_err:.2e} exceeds threshold {MAX_ABS_ERR:.1e}"
    )
